### PR TITLE
Handle empty manifest

### PR DESCRIPTION
**Pull request by jmcarp**

### CODE REVIEW

**Comment by jmcarp** [comment]
Pointed concourse at this branch to verify--working as expected.

**Comment by cnelson** [comment]
What causes bosh to do this?

**Comment by jmcarp** [comment]
Looks like `manifest` is `None` if the director tried to roll out a deployment for the first time and failed. This is currently happening on staging because I haven't fixed `logsearch-platform` so that I could verify this. We can just fix the broken deployment, but I figured it was easy enough to handle the edge case.

**Comment by cnelson** [comment]
👍 wasn't suggesting we don't fix it, just wanted to understand the cause. its not intuitive to me that bosh could return null for a manifest.

**Pull request merged**
